### ISSUE TITLE
Save failed

### ISSUE THREAD

**Issue by XiaoCC** [darx/IndexedDBEdit#15]
helpers.js:44 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'transaction')
    at helpers.js:44:31
    at Array.forEach (<anonymous>)
    at qo.Ts (helpers.js:42:11)
    at index.mjs:972:20
    at Array.forEach (<anonymous>)
    at index.mjs:971:31
    at C.u [as save] (JSONEditor.svelte:51:5)
    at v (App.svelte:54:12)
    at So.<anonymous> (App.svelte:84:39)
    at index.mjs:972:20

**Comment by XiaoCC** [comment]
ace.js:3621 
        
       Could not load worker TypeError: e.split is not a function
    at ace.define.t.moduleUrl (ace.js:3749:22)
    at ace.define.$createWorkerFromOldConfig (ace.js:19120:45)
    at new l (ace.js:19098:50)
    at h.createWorker (json.js:300:22)
    at f.$startWorker (ace.js:9779:39)
    at f.$onChangeMode (ace.js:9735:18)
    at f.<anonymous> (ace.js:9715:22)
    at ace.define.t.loadModule (ace.js:3787:26)
    at f.setMode (ace.js:9704:16)
    at f.set (ace.js:10979:35)

**Comment by XiaoCC** [comment]
Notification.svelte:13 
        
       Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.

**Comment by dawidl022** [comment]
I've noticed two things while trying this feature of the extension out:

1. The `Uncaught TypeError: Cannot read properties of undefined (reading 'transaction')` at `helpers.js:44` occurs when the target table is empty (i.e. `[]`). I managed to work around this by populating the table with a dummy record in the web application, then importing my data and saving it.
2. I've encountered severe performance issues. I'm unsure if this is a bug in the IndexedDBEdit extension, the web application itself, or Chrome. It seems to take ~30s per 1000 lines of imported JSON. During this time, the `Google Chrome Helper (Renderer)` process is at full CPU usage and depending on the table, the UI of the web app can also be unresponsive.

(I'm on an M1 Pro Macbook, running macOS 13.5.2, Chrome 118)
